post http://localhost:3000/add-location
Content-Type: application/json

{
    "name":"mike",
    "email":"whogivesafuck@gmail.com",
    "location_description": "vawlence everywhere",
    "website": "www.wahala.com",
    "phone":"23"
}